# -*- coding: utf-8 -*-
"""streamlite project one.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ik1gzlHh2Dra4kAznnp_lQ1An96syKkz
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Title
st.title("📊 Sales Data Analysis Dashboard")

# File uploader
uploaded_file = st.file_uploader("Upload your CSV file", type=["csv"])

if uploaded_file is not None:

    # STEP 1: LOAD DATA
    df = pd.read_csv(uploaded_file, encoding='latin1')

    st.subheader("🔍 Data Preview")
    st.write(df.head())

    # STEP 2: CLEAN COLUMNS
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

    st.write("Cleaned Columns:", df.columns)

    # STEP 3: DATE CONVERSION
    if 'order_date' in df.columns:
        df['order_date'] = pd.to_datetime(df['order_date'])
    else:
        st.warning("Column 'order_date' not found")

    # STEP 4: REMOVE MISSING VALUES
    df = df.dropna()

    # STEP 5: TOP PRODUCTS
    st.subheader("🏆 Top 10 Products")
    top_products = df.groupby('product_name')['sales'].sum()
    top_products = top_products.sort_values(ascending=False).head(10)

    st.bar_chart(top_products)

    # STEP 6: REGION PERFORMANCE
    st.subheader("🌍 Region Performance")
    region_sales = df.groupby('region')['profit'].sum()
    st.bar_chart(region_sales)

    # STEP 7: CATEGORY PERFORMANCE
    st.subheader("📦 Category Performance")
    category_sales = df.groupby('category')['sales'].sum()

    fig1, ax1 = plt.subplots()
    ax1.pie(category_sales, labels=category_sales.index, autopct='%1.1f%%')
    ax1.set_title("Category Distribution")
    st.pyplot(fig1)

    # STEP 8: MONTHLY TREND
    st.subheader("📈 Monthly Sales Trend")

    if 'order_date' in df.columns:
        df['month'] = df['order_date'].dt.to_period('M').astype(str)
        monthly_sales = df.groupby('month')['sales'].sum()

        st.line_chart(monthly_sales)
    else:
        st.warning("Cannot create monthly trend (order_date missing)")